# Generated by Django 5.0.6 on 2024-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('member', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('num_of_guests', models.IntegerField()),
                ('table_no', models.CharField(max_length=20)),
                ('bar_or_restaurant', models.CharField(choices=[('Bar', 'Bar'), ('Restaurant', 'Restaurant')], max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
