# Generated by Django 5.0.6 on 2024-06-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('member', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('num_of_guests', models.IntegerField()),
                ('table_no', models.CharField(max_length=10)),
                ('bar_or_restaurant', models.CharField(max_length=15)),
                ('date_time', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='bar_or_restaurant',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='guest',
            name='table_no',
            field=models.CharField(max_length=10),
        ),
    ]
