# Generated by Django 5.0.6 on 2024-06-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_deletedguest_alter_guest_bar_or_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedGuest',
        ),
        migrations.AddField(
            model_name='guest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
